### PR TITLE
#163426533 Implement email and in app notification

### PR DESCRIPTION
**Pull request by biolabalo**
#### What does this PR do?
* Implement email and In-app notification when certain events happen
#### Description of Task to be completed?
Have the following endpoints working:

* Enable In-app notification:  PATCH `localhost:3000/api/v1/notifications/inApp`
* Opt out of  In-app notification:  PATCH `localhost:3000/api/v1/notifications/inApp`
* Enable email notification:  PATCH `localhost:3000/api/v1/notifications/email`
* Opt out of email notification:  PATCH `localhost:3000/api/v1/notifications/email`

Implemented the following functionalities
* Enable notification when a bookmarked article has a new reaction
* Enable notification when a user has a new follower
* Enable notification when a user you follow publishes an article 

#### How should this be manually tested?
* clone the repo
* run `npm install` to install new packages (Pusher)
* Make sure at least two users are created, a user has an article in the database, the user has at least a follower and has bookmarked an article
* fire up postman
* navigate to PATCH `localhost:3000/api/v1/notifications/inApp` to opt in for In-app notification
* navigate to PATCH `localhost:3000/api/v1/notifications/email` to opt in for email notification
* navigate to POST `http://localhost:3000/api/v1/profiles/<name of the user to follow>/follow` to follow  the user, the user will receive an email and In-app notification

#### What are the relevant pivotal tracker stories?
[#163426533](https://www.pivotaltracker.com/story/show/163426533)
#### Screenshots (if appropriate)

image
image
image
image
image
[image](https://user-images.githubusercontent.com/22154654/53790246-d799d180-3f26-11e9-969b-093ccc0ac194.png)
image

### CODE REVIEW

**Comment by omenkish** [comment]
How did the test coverage drop by 2.8?

**Review by bobbylemm — DISMISSED** [review]
LGTM

**Review by ozone4real — DISMISSED** [review]
LGTM

**Comment by biolabalo** [comment]
> How did the test coverage drop by 2.8?

If you check the coverage file, you would see that there are lines I can't test because
(1) The functions are being called inside the controller, they do not return any values they just perform actions in the controllers.

**Review by bobbylemm — DISMISSED** [review]

**Review by primuse — DISMISSED** [review]

**Review by primuse — APPROVED** [review]

**Review by EfeAgare — APPROVED** [review]

**Pull request merged**
