### PR TITLE
#163426513 Configure Eslint

### PR DESCRIPTION
**Pull request by bobbylemm**
**What does this PR do?**
Configure Eslint

**Relevant pivotal tracker stories**
[#163426513](https://www.pivotaltracker.com/story/show/163426513)

### CODE REVIEW

**Review by primuse — APPROVED** [review]
Looks good to me

**Comment by EfeAgare** [comment]
The commit message should be: configure eslint not configures eslint

**Comment by p-funky** [comment]
@EfeAgare `configures` is actually correct. You might want to take a second look at the conventions.

**Comment by EfeAgare** [comment]
@p-funky The document says **use imperative, present tense: “change” not “changed” nor “changes”**

**Comment by p-funky** [comment]
@EfeAgare apparently you are right. My bad.
@bobbylemm please amend accordingly. Plus considering this is a chore and not a feature, your commit message should have started with `ch` and not `feat`.

**Comment by bobbylemm** [comment]
@p-funky I have implemented the feedback

**Comment by p-funky** [comment]
@bobbylemm The feedback was primarily for your *commit* message even though it affected your PR description as well.

**Comment by bobbylemm** [comment]
@p-funky I have corrected the commit message.

**Review by EfeAgare — APPROVED** [review]

**Review by divinediscipline — APPROVED** [review]

**Comment by p-funky** [comment]
@bobbylemm your PR title is also off. Kindly check https://github.com/andela/engineering-playbook/tree/master/5.%20Developing/Conventions#branch-naming again and make necessary adjustments.

**Comment by bobbylemm** [comment]
@p-funky I have reviewed the engineering playbook and made the necessary adjustments

**Pull request merged**
