### PR TITLE
#163426512 Configure Authors Haven to use PostgreSQL as DB Engine and Setup Babel

### PR DESCRIPTION
**Pull request by biolabalo**
#### What does this PR do?
- Configure Authors Haven to use PostgreSQL as DB Engine
- Setup Babel to transpile newer javascript features to ES5

 #### What are the relevant pivotal tracker stories?
- [#163426512](https://www.pivotaltracker.com/story/show/163426512)

### CODE REVIEW

**Comment by omenkish** [comment]
Nice job @biolabalo. You might want to check this path db/config/config.js the test and production objects have dialects 'Mysql' instead of postgres.

The babel dependencies installed are version 6, can you update to the recent versions?
Some codes are in ES5, specifically .sequelizerc file

**Comment by divinediscipline** [comment]
some of your files like the user.js and sequelizerc are using es5. Kindly review and change to es6

**Review by bobbylemm — DISMISSED** [review]
this looks good to me

**Comment by EfeAgare** [comment]
This looks good to me, but it's showing conflicts in ***package-lock.json***,  ***package.json***. Check those out

**Review by EfeAgare — DISMISSED** [review]

**Review by bobbylemm — DISMISSED** [review]
looks good to me

**Review by p-funky — APPROVED** [review]

**Review by EfeAgare — APPROVED** [review]

**Pull request merged**
