### PR TITLE
#163693092 setup model tests

### PR DESCRIPTION
**Pull request by omenkish**
#### What does this PR do?
Ensure that models and their relationships are working as expected.

#### Description of Task to be completed?
Have the following models tested to ensure that they conform to what was defined
  `Users model`
  `Articles model`
  `Comments model`
  `Bookmarks model`
  `Follows model`
  `Reports model`
  `Reactions model`

#### How should this be manually tested?
Clone the repository, cd into it, install dependencies, and run the command `npm run test`

#### What are the relevant pivotal tracker stories?
[#163693092](https://www.pivotaltracker.com/story/show/163693092)

### CODE REVIEW

**Comment by EfeAgare** [comment]
The PR title does not follow team convention. Please recheck the title

**Comment by omenkish** [comment]
> The PR title does not follow team convention. Please recheck the title

Thanks for pointing this out, I have updated it accordingly.

**Review by EfeAgare — DISMISSED** [review]

**Review by bobbylemm — DISMISSED** [review]
LGTM

**Comment by p-funky** [comment]
Isn't `tests` a better name for the folder housing tests? 🤔
Also, I think it would be better if these tests were put in a folder under the tests directory called `models` and also that the tests should be named after their files i.e. pluralized names such as `users.test.js`.

**Comment by p-funky** [comment]
You'll also need to update your description in your PR under "Description of Task to be completed?" to `Articles` model.

**Comment by omenkish** [comment]
> Isn't `tests` a better name for the folder housing tests? 🤔
> Also, I think it would be better if these tests were put in a folder under the tests directory called `models` and also that the tests should be named after their files i.e. pluralized names such as `users.test.js`.

> I had them in `models` folder but I realized the test was only affecting that folder. @bobbylemm had a test file for authentication which was working well but introducing that `models` folder somehow stopped the authentication test from running.
> Pluralizing the test files is a good idea, I will do that.

**Comment by omenkish** [comment]
> You'll also need to update your description to `Articles` model.

 I don't understand this. Which description exactly?

**Review by p-funky — APPROVED** [review]

**Pull request merged**
